version: '3.9'
services:
  minio:
    image: minio/minio:RELEASE.2022-09-17T00-09-45Z.hotfix.4bb22d5cd
    container_name: 'minio'
    ports:
      - 9000:9000
      - 9001:9001
    command: server --console-address ":9001" /data
    volumes:
      - ./tmp/minio/data:/data
  app:
    build: .
    container_name: 'app'
    environment:
      - S3_REGION=ap-northeast-1
      - S3_BUCKET=bucket
      - S3_PREFIX=speech/
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY_ID=minioadmin
      - S3_SECRET_ACCESS_KEY=minioadmin
      - S3_FORCE_PATH_STYLE=1
    volumes:
      - ./tmp/:/app/tmp/
      - ./web.rb:/app/web.rb
      - ./worker.rb:/app/worker.rb
    ports:
      - 4567:4567
